apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-mgmt-deployment
  labels:
    app: student-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-mgmt
  template:
    metadata:
      labels:
        app: student-mgmt
    spec:
      containers:
      - name: student-mgmt
        image: gunnapradeepreddy/student-mgmt:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
